### ISSUE TITLE
Publish as a package

### ISSUE THREAD

**Issue by RomanGotsiy** [APIs-guru/graphql-voyager#1]
Publish as a package which users can deploy to their site

**Comment by tlvenn** [comment]
Amazing lib guys, any chance to publish it to npm soon ?

**Comment by RomanGotsiy** [comment]
@tlvenn we've published the first rc.0 release.

Check it out and let us know if you have any issues with it.

**Comment by tlvenn** [comment]
Awesome, thanks guys !

**Comment by OlegIlyenko** [comment]
Thanks for the awesome work! I tried to use rc.0 in another project (graphiql-workspace), but faced some issues. It would be great if you could look at it:

https://github.com/OlegIlyenko/graphiql-workspace/issues/17#issuecomment-285722182

**Comment by mydearxym** [comment]
any progress on this?

**Comment by IvanGoncharov** [comment]
@mydearxym Yes it's already published on NPM: https://www.npmjs.com/package/graphql-voyager
Documented here: https://github.com/APIs-guru/graphql-voyager#using-as-a-dependency

Plus you can use Express, Hapi, Koa middleware: 
https://github.com/APIs-guru/graphql-voyager#using-as-a-dependency

@RomanGotsiy It probably makes sense to close this issue?

**Comment by mydearxym** [comment]
thanks @IvanGoncharov , but i can't run voyager with [next.js](https://github.com/zeit/next.js) project, maybe it's the config issue , i will check it later

**Comment by RomanGotsiy** [comment]
@IvanGoncharov yes, closing this

@mydearxym open a separate issue for this!
