### ISSUE TITLE
Issue loading introspective schema

### ISSUE THREAD

**Issue by stevenmckinnon** [APIs-guru/graphql-voyager#104]
Hi, 

I’m trying to implement voyager at the moment to my project. 

I’ve followed the same format as the demo folder to load in the [.json files](https://github.com/APIs-guru/graphql-voyager/tree/master/demo/presets) then pass them as props via [this](https://github.com/APIs-guru/graphql-voyager/blob/master/demo/presets.ts) to the **GraphQLVoyager** like [here](https://github.com/APIs-guru/graphql-voyager/blob/master/demo/index.tsx) component, however I get 

`TypeError: Object(...) is not a function at getSchema`

Can anyone assist?

**Comment by stevenmckinnon** [comment]
Issue was related to my version of GraphQL which was too old for the required functions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TSMMark** [comment]
I'm on the latest `14.2.1` version of graphql and still getting this. Any ideas?

I also have this alias in my webpack config to make sure all packages are using the same graphql module

```js
resolve: {
  alias: {
    graphql: path.resolve('./node_modules/graphql'),
```

**Comment by IvanGoncharov** [comment]
@TSMMark Can you please run `npm ls graphql` and post the output here?

**Comment by TSMMark** [comment]
I ended up trapped in @babel dependency hell and abandoned the task of adding this package. Please forget about me, thanks for your time ❤️
