### ISSUE TITLE
Feature Request: Paste schema directly into textbox

### ISSUE THREAD

**Issue by yoDon** [APIs-guru/graphql-voyager#106]
Perhaps this is already available and I just missed it... it would be great to be able to use graphql-voyager while designing a schema, pasting the in-progress schema directly into a textbox rather than having to keep publishing work-in-progress copies of the schema just to be able to download them into visualizer.

**Comment by romain-gilliotte** [comment]
When cloning the repo, and running npm run start, the option seem to be already available.

![image](https://user-images.githubusercontent.com/1374063/54879547-6de05980-4e3a-11e9-8dbe-d4d79489e0f3.png)

**Comment by IvanGoncharov** [comment]
@romain-gilliotte Yes it's in `master` but not yet deployed to:
https://apis.guru/graphql-voyager/

Currently, Voyager is under heavy refactoring in preparation for `1.0.0`.
Plus we want to improve DX of the demo.

**Comment by yoDon** [comment]
Nice! Did you want to keep this open to track the work until it's published on the site? I'm ok with having the issue closed knowing it's in the branch

**Comment by IvanGoncharov** [comment]
@yoDon Thanks. We are working on stabilizing demo ATM and plan to publish it tomorrow.
