### ISSUE TITLE
Error in production on Heroku

### ISSUE THREAD

**Issue by thebetternewt** [APIs-guru/graphql-voyager#109]
Hi. Great graphQL plugin! Thank you!

I am having an issue deploying to Heroku with express. I am actually using `apollo-server-express` for my server. Voyager works perfectly fine when running in development locally, but when deployed to production, I get the following error: 

`TypeError: Cannot read property '__schema' of undefined`

I get the "Loading..." screen, and then Voyager flashes for a moment. Then things go blank and I get the error message in the console along with a `POST 400 Bad Request` error.

Is there something special I need to do to get Voyager to work with Express running on Heroku?

Thanks!

**Comment by IvanGoncharov** [comment]
@thebetternewt `apollo-server-express` disable introspection in production:
> The default behavior of apollo-server's integrated graphql-playground is for it to be disabled (along with introspection queries) when `NODE_ENV=production`.

https://github.com/apollographql/apollo-server/issues/1571#issuecomment-415999534

**Comment by crimbler2** [comment]
For anyone stumbling over this, the issue can be fixed by setting the MaximumQueryDepth param to a really high number or simply removing it. This is not something you wanna do for production, ofc.
