### ISSUE TITLE
Change from queries to mutations

### ISSUE THREAD

**Issue by elenigen** [APIs-guru/graphql-voyager#111]
How to display the mutations or the queries from a Change Introspection? (from a flat HTML version)
I found this issue was closed, but I don't really understand how to make it happen: https://github.com/APIs-guru/graphql-voyager/issues/15

Thanks!

**Comment by IvanGoncharov** [comment]
@elenigen Do you mean online demo https://apis.guru/graphql-voyager/ or NPM package?

**Comment by IvanGoncharov** [comment]
@elenigen If you use NPM, can you please check that you are using `v1.0.0-rc.26`?

**Comment by elenigen** [comment]
Sorry, I just noticed that we can actually simply change the root item from the menu :
![image](https://user-images.githubusercontent.com/8632319/54408140-01858d80-46b7-11e9-911a-ab6ac2c97cc2.png)
I believe I was focusing too much on the `displayOptions.rootType` feature.  I thought it could be initialized only when the Voyager page is loaded, but in the end, it's dynamic.
🤦‍♂️ 

Thanks anyway for your help!

**Comment by kub1x** [comment]
I had the very same problem and had to find this thread to figure it out. 
Totally missed the little chevron icon on the menu box. 
I was looking rather for a "change introspection" button somewhere up in top left corner.

**Comment by LouisAmon** [comment]
Coming way after last comment but I totally missed the chevron as well

Wouldn't it make much more sense to have a an abstract "Root" which then contains "Query", "Mutation" and Subscription" (and henceforth for their endpoints) ?

This way we wouldn't need the chevron menu as much and would be able to search any endpoint in the search bar
