### ISSUE TITLE
Can't visualize OneGraph API

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [APIs-guru/graphql-voyager#118]
E.g.: https://apis.guru/graphql-voyager/?url=https://serve.onegraph.com/dynamic?app_id%3D1b2b8f9d-f2de-49a7-b5d6-46c313ddc203

"Transmitting..." is displayed forever. No errors in the browser console. What could be the problem?

**Comment by IvanGoncharov** [comment]
@FluorescentHallucinogen You graph is so huge it takes 189s to render on my laptop.
![image](https://user-images.githubusercontent.com/8336157/58634106-1f947e80-82f3-11e9-87b0-81b1ca2e10d0.png)
