### ISSUE TITLE
Many errors when I execute `npm run build:release`: error TS2300: Duplicate identifier 'LibraryManagedAttributes'

### ISSUE THREAD

**Issue by harobed** [APIs-guru/graphql-voyager#124]
Many errors when I execute `npm run build:release`:

```
error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
...
```

complete error: https://gist.github.com/harobed/7c3a0acf4544a19297d7c53d20dcd353

**Comment by IvanGoncharov** [comment]
@harobed Thanks for reporting 👍 
Already fixed on `master` 🎉
