### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by felipesabino** [APIs-guru/graphql-voyager#13]
## Issue

When running a custom introspection query from live demo, the UI does not allow me to proceed as the button is showing the error 

```
TypeError: Cannot read property 'type' of undefined
```

## Resources

The introspection query (copied from the demo page) and the result can be found at:

- Query:  https://gist.github.com/felipesabino/2be0c0c1c02ec190232790575fa532a3#file-introspection-query-txt
- Result: https://gist.github.com/felipesabino/2be0c0c1c02ec190232790575fa532a3#file-introspection-result-txt

**Comment by RomanGotsiy** [comment]
hey @felipesabino.
Thanks for reporting. The issue is caused by bug in relay detection code. I will fix it ASAP.

**Comment by RomanGotsiy** [comment]
@felipesabino the issue is fixed
you have to untick "Skip Relay" option though to get your graph unchanged.

We will fix this in the future by not showing or disabling "Skip Relay" option for non-relay APIs.

**Comment by felipesabino** [comment]
Thanks @RomanGotsiy, I just tested and it works fine 👍

**Comment by starriv** [comment]
> Thanks @RomanGotsiy, I just tested and it works fine 👍

emm, I also encountered this problem. Still not fixed yet?
