### ISSUE TITLE
Doesn't render with empty interfaces

### ISSUE THREAD

**Issue by avwie** [APIs-guru/graphql-voyager#133]
I have an empty interface, with concrete implementations for all the subtypes and it works perfect. However, in your visualisation is it not possible and I get a console error.

**Comment by IvanGoncharov** [comment]
@avwie GraphQL requires that the interface is always not empty:
> An Interface type must define one or more fields.
https://graphql.github.io/graphql-spec/draft/#sel-HAHblBFBABABxB4a
