### ISSUE TITLE
Interfaces and Types must define one or more fields => NOT true

### ISSUE THREAD

**Issue by mikaelparkefelt** [APIs-guru/graphql-voyager#137]
In our Grapql Schema we have empty interfaces and types with no members.

**This is causing the following error:**
_Type {{Interface or Type}} must define one or more fields.
    at Ai (main.js:129)
    at main.js:129
    at Yi (main.js:129)
    at main.js:129
    at ya (main.js:129)
    at Aa (main.js:129)
    at n.updateIntrospection (main.js:129)
    at n.fetchIntrospection (main.js:129)
    at n.componentDidUpdate (main.js:129)
    at Jr (main.js:57)
cr @ main.js:57
Nr.t.callback @ main.js:57
ar @ main.js:57
ir @ main.js:57
Jr @ main.js:57
zr @ main.js:57
(anonymous) @ main.js:57
n.unstable_runWithPriority @ main.js:66
Dl @ main.js:57
Ol @ main.js:57
Sl @ main.js:57
Pl @ main.js:57
Et @ main.js:57_

I woud say this is a bug. Interfaces and types are still valid even if they do not have any members.

**Comment by IvanGoncharov** [comment]
@mikaelparkefelt GraphQL requires that the interface is always not empty:
> An Interface type must define one or more fields.
https://graphql.github.io/graphql-spec/draft/#sel-HAHblBFBABABxB4a
