### ISSUE TITLE
allow two underscores in input objects

### ISSUE THREAD

**Issue by VladimirAlexiev** [APIs-guru/graphql-voyager#145]
Voyager complains about `__typename` in this piece of a query schema:

```graphql
     "Ordering of scalars"
     enum _OrderBy {ASC DESC}

     "Order fields of Object"
     input Object_OrderBy {
       id:         _OrderBy
       __typename: _OrderBy
     }
```

Two underscores are indeed reserved for https://graphql.github.io/graphql-spec/draft/#sec-Type-Name-Introspection, but that pertains to (output) objects, not input objects. GraphiQL and graphql-java have no problem with such input field name. Please allow it.

For the time being we've implemented a workaround by using one underscore in the input object. But this creates an unpleasant inconsistency:

```graphql
query AllObjects(orderBy: {_typename: ASC, id: DESC}) {
  id
  __typename
}
```

**Comment by IvanGoncharov** [comment]
> Two underscores are indeed reserved for graphql.github.io/graphql-spec/draft/#sec-Type-Name-Introspection, but that pertains to (output) objects, not input objects.

Please see: https://graphql.github.io/graphql-spec/draft/#sel-IAHhBVDDBDCAACCTx5b
> The input field must not have a name which begins with the characters "__" (two underscores).

> GraphiQL and graphql-java have no problem with such input field name. Please allow it.

Newer versions of GraphiQL will also crash with an identical error.
We supported such names for more than a year to allow the community to migrate but now it's removed from `graphql-js` so both Voyager and GraphiQL will always crash:
https://github.com/graphql/graphql-js/pull/2129/files#diff-1f3d3db86726f8374219736d892f2164L94

**Comment by VladimirAlexiev** [comment]
Thanks for the clarifications!
