### ISSUE TITLE
Website flagged for Ethereum Phishing

### ISSUE THREAD

**Issue by pietro909** [APIs-guru/graphql-voyager#149]
Hi there,
got this message while trying to access the website:

![Screenshot 2020-02-01 at 19 02 45](https://user-images.githubusercontent.com/2094604/73596752-73f89980-4525-11ea-806a-f35048abfc13.png)

From
https://github.com/metamask/eth-phishing-detect

**Comment by IvanGoncharov** [comment]
@pietro909 Thanks for taking time to report it and especially for figure out a proper repo to report it 👍 
Reported here https://github.com/MetaMask/eth-phishing-detect/issues/3636
