### ISSUE TITLE
Argument of type [String!] is shown as type [String]!

### ISSUE THREAD

**Issue by Apollinaire** [APIs-guru/graphql-voyager#151]
The following type definition:
```grapqhl
type Foo {
  bar(baz: [String!]): String
}
```

is incorrectly displayed in the left panel, where the position of the exclamation mark is wrong.

```
bar(
  baz: [String]!   # should be baz: [String!]
): String
```

Screenshot: 
![image](https://user-images.githubusercontent.com/5938985/73766254-11e2a300-4776-11ea-90ff-f37da21dce82.png)

**Comment by IvanGoncharov** [comment]
@Apollinaire Thanks for reporting 👍 
Fixed both in the demo and release `graphql-voyager@1.0.0-rc.29` 📦
