### ISSUE TITLE
Ability to use a schema.graphql as preset

### ISSUE THREAD

**Issue by LunaticMuch** [APIs-guru/graphql-voyager#152]
Hi,

I am working on the last public version. I am looking to change it in a way I can use a schema.graphql as input preset rather than an introspection. 

The first attempt on presets.ts was

```typescript
import { buildSchema, introspectionFromSchema } from 'graphql/utilities';
const rtbSchema = introspectionFromSchema(buildSchema('./presets/rtb.graphql'));

export const PRESETS = {
  'rtbSchema': rtbSchema
};

export const defaultPresetName = 'rtbSchema';
export const defaultPreset = PRESETS[defaultPresetName];
```
but it failed on compilation

```bash
ERROR in /x/graphql/graphql-voyager/demo/index.tsx
[tsl] ERROR in /x/graphql/graphql-voyager/demo/index.tsx(27,7)
      TS2741: Property '__schema' is missing in type '(introspectionQuery: any) => Promise<any>' but required in type 'IntrospectionQuery'.
```

Am I completely wrong here?

Thanks
LM

**Comment by sanketCactus** [comment]
Do we have this feature to use schema directly or it only works with introspection query?

**Comment by IvanGoncharov** [comment]
@LunaticMuch Sorry for the late response.
You need to change this line:
```js
const rtbSchema = {
  data: introspectionFromSchema(buildSchema('./presets/rtb.graphql')),
};
```

**Comment by LunaticMuch** [comment]
It works in theory, but not in practice. `buildSchema` interprets the file path as a string rather than a source file.
Even using a construct like:

```javascript
const mySchemaFile= fs.readFileSync('./presets/schema.graphql', 'utf8');
const mySchema = {data: introspectionFromSchema(buildSchema(mySchemaFile))};
```
does not solve. Possibly an issue with `graphql-js`

**Comment by tony** [comment]
Hi there!

I'm a bit confused. I don't see an example of a schema file working with graphql-voyager.

In the example given, it's very abstract, across multiple files, and basically not a schema file.  

I was sort of expecting a couple of lines of JS. Reading a schema file and showing it in a react component.  That would be an example in terms of what I'm looking for. 🤷

**Comment by LunaticMuch** [comment]
@tony to use a schema file (SDL), you need to make three changes:

1. In `presets.ts` you must import the following `import {buildSchema, introspectionFromSchema} from 'graphql'`
2. In `presets.ts` you generate the introspection in a way like this: 
```
const mySDL = require('./presets/mySDL.graphql'
const myIntrospectionFromSchema = {data: introspectionFromSchema(buildSchema(mySDL))}
```
3. In `webpack.demo.js` (or `webpack.js` depending what you're trying to do) you must tell webpack how to deal with a graphql file. Here what you need:
```      
{
        test: /\.graphql$/,
        use:[{loader: 'raw-loader',options:{esModule: false}}]
      }
```

Also, you must install `raw-loader` with `npm install -D raw-loader`. It makes webpack able to read the graphql file and treat is a string.

Let me know if you need to see a working demo or if you have a repo where I can help you.
