### ISSUE TITLE
Add heat map ability

### ISSUE THREAD

**Issue by mmaico** [APIs-guru/graphql-voyager#154]
Hi guys, i'm working on a project where it is necessary to see which graph nodes are being used by customers and which customers are using them. I am working on this feature and I would like to know if it makes sense for us to add to the project. I'm using Apollo Server and developing a plugin that will heat the node called by customers.

 I am thinking of changing the colors of the "tables" according to the number of calls it receives and gray for "tables" node not used

**Comment by IvanGoncharov** [comment]
@mmaico I built a similar project on top of Voyager for my conference talk:
![demo](https://user-images.githubusercontent.com/8336157/76617982-1e55da80-6530-11ea-8c1e-e7053a5966a3.gif)

Here is source code: https://github.com/APIs-guru/graphql-coverage
So you can achieve this functionality without modification of Voyager.

**Comment by mmaico** [comment]
Niceeeeee... I'll look this project. Thanks man!
