### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by DrYSG** [APIs-guru/graphql-voyager#155]
I am not seeing subscriptions. Is this a feature request?

**Comment by DrYSG** [comment]
BTW, I also tried looking at: 
https://swapi.graph.cool/ with voyager,

and when I expand the queries root, I don't see the mutations.

**Comment by IvanGoncharov** [comment]
@DrYSG Strange, for `swapi.graph.cool` I see subscriptions in the list:
![image](https://user-images.githubusercontent.com/8336157/76617567-3b3dde00-652f-11ea-9c3d-53ba6f8f7990.png)

Can you reproduce it using our demo: https://apis.guru/graphql-voyager/

**Comment by DrYSG** [comment]
Must be I don't understand the interface. I don't see anything like what you show when I go to the demo page. (which I assume the star wars schema is swapi.graph.cool,

![image](https://user-images.githubusercontent.com/2865368/76633537-4424b480-651b-11ea-9656-c1b9bfc192b0.png)

**Comment by IvanGoncharov** [comment]
> which I assume the star wars schema is swapi.graph.cool,

@DrYSG StarWars schema is official https://graphql.org/swapi-graphql/ that only has Query.
You can try different APIs by clicking `Change Schema` and then switching to `Introspection` tab.

> Must be I don't understand the interface.

You need to select root type from drop-down list on the floating panel.
![image](https://user-images.githubusercontent.com/8336157/76636672-20c92c00-6552-11ea-8c1b-add7dc656649.png)

**Comment by Nishchit14** [comment]
@DrYSG Here you can directly review the schema graph with FireQL.

http://fireql.dev/?url=https://swapi.graph.cool/graphql (just click on `Chart` button)

Also just created a video with it here, https://youtu.be/j6UF357qwSE

I hope it will hepl!!

**Comment by DrYSG** [comment]
As I suspected, my ignorance. I was missing the fact that the pop-up had a dropdown that could be switched between Query, Mutate, and Subscribe, So I was not see in the first clip you showed. The video made things really clear.

I was testing this against my RUST (JUNIPER) based server, which had subscriptions.  introspection is also working there, and thanks for the fireql link. I don't think that will help with my intra-net site which is not on the internet.

**Comment by Nishchit14** [comment]
Great, I'm happy that it answered your question. 

Yes, I can understand your concern about security. https://fireql.dev is a part of https://firecamp.io, If you're using **WebSocket or GraphQL** then you can give it a try. we're still in beta and hearing a lot of feedback from our users.

**Comment by DrYSG** [comment]
I use insomnia or postman for our offline site. But no WS with them. Postwoman, looks interesting. But yours looks best for subscribing.

**Comment by FluorescentHallucinogen** [comment]
@DrYSG 
> I was missing the fact that the pop-up had a dropdown that could be switched between Query, Mutate, and Subscribe

You're not alone. See e.g. #135. Looks like a bad UX.
