### ISSUE TITLE
Search on type list

### ISSUE THREAD

**Issue by RomanGotsiy** [APIs-guru/graphql-voyager#16]
suggested by @blntylmn in #15

**Comment by praveensastry** [comment]
Hi @RomanGotsiy , I am using this awesome tool, and i found that the ability to search on type list is really handy. I would like to assign this to myself if this is still open.

**Comment by RomanGotsiy** [comment]
@praveensastry, it would be awesome. Thanks!

**Comment by clemens-tolboom** [comment]
Any result?

**Comment by FluorescentHallucinogen** [comment]
Here is my vision. :wink:

Before: 
![before](https://user-images.githubusercontent.com/7892779/52909999-20545800-32a2-11e9-838d-cb9007ae0009.png)

After:
![after](https://user-images.githubusercontent.com/7892779/52910001-26e2cf80-32a2-11e9-9a9c-51cb3731f810.png)

**Comment by FluorescentHallucinogen** [comment]
It would also be great to be able to search by fields too, not only by types:

![voyager-search](https://user-images.githubusercontent.com/7892779/52970726-fa27d880-33c5-11e9-98ee-5ed1b0271bf0.png)

**Comment by IvanGoncharov** [comment]
Search for both types and fields implemented on `master` and released as `v1.0.0-rc.27`.
We are still working on updating demo.
