### ISSUE TITLE
Incompatibility with graphql@15.0.0+

### ISSUE THREAD

**Issue by JeffJankowski** [APIs-guru/graphql-voyager#162]
It looks like there is some breaking changes in version 15+ of the graphql library in regards to fetching the introspection query.

Any function passed to the `introspection` property of the the Voyager component receives `undefined` for the `query` parameter. A cursory glance at the graphql-voyager code looks like the following line can no longer resolve from the graphql/utilities peer dependency:

`var promise = this.props.introspection(utilities_["introspectionQuery"]);`

The fix is probably as simple as refactoring the method name from `instrospectionQuery` to `getIntrospectionQuery`. Regardless, I **downgraded to my graphql package to ^14.5.8,** which seemed to fix the issue.

**Comment by IvanGoncharov** [comment]
@JeffJankowski Thanks for taking the time to report it and even more for detailed investigation 👍 
The funniest part is that I'm the maintainer of `graphql` package and removed `introspectionQuery` myself 🤦 
I will try to release fix ASAP.

**Comment by IvanGoncharov** [comment]
@JeffJankowski Fixed and released as `v1.0.0-rc.30` 🎉 
Can you please test?

**Comment by JeffJankowski** [comment]
@IvanGoncharov Looks good on my end. Appreciate the quick patch!
