### ISSUE TITLE
Import by nginx or CDN

### ISSUE THREAD

**Issue by joserochadocarmo** [APIs-guru/graphql-voyager#19]
Why can not I import from a CDN or NGINX?
    ```
    <head>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>
    <script src="https://apis.guru/graphql-voyager/releases/v1.x/voyager.min.js" ></script>
    <link rel="stylesheet" href="https://apis.guru/graphql-voyager/releases/v1.x/voyager.css"/>
    </head>
```
Error:
Uncaught DOMException: Failed to construct 'Worker': Script at 'https://apis.guru/graphql-voyager/releases/v1.x/voyager.worker.js' cannot be accessed from origin 'http://localhost:3000'.

**Comment by RomanGotsiy** [comment]
@joserochadocarmo sorry for long reply. We are busy with other projects right now.
I will investigate and let you know ASAP.

**Comment by RomanGotsiy** [comment]
@joserochadocarmo could you check with the latest version?
I changed worker to load over XHR so should support CORS now

**Comment by joserochadocarmo** [comment]
Work!!! Thanks a lot man!!!
