### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jvallarvisp** [APIs-guru/graphql-voyager#20]
Uncaught SyntaxError: Unexpected token < voyager.worker.js:1

```
<!DOCTYPE html>
<html>
<head>
....
```

**Comment by RomanGotsiy** [comment]
@jvallarvisp sorry for long reply. We are busy with other projects right now.
I will investigate and let you know ASAP.

**Comment by RomanGotsiy** [comment]
@jvallarvisp I guess you may be getting 404 page.
Could you check from developers tools => network tab what is the response for `voyager.worker.js`
