### ISSUE TITLE
With nestjs

### ISSUE THREAD

**Issue by kamalkech** [APIs-guru/graphql-voyager#207]
On documentation cannot found how can implemented with nestjs !

**Comment by tjsearsz** [comment]
@kamalkech  Maybe there is a "nestjs way" to implement it, but I was able to make voyager work by calling it on main.ts. Similar as the documentation states:

![image](https://user-images.githubusercontent.com/11713783/132071707-8a387eb2-0791-4070-ada5-7dc3115af9b7.png)


![image](https://user-images.githubusercontent.com/11713783/132071747-ec2f162d-79e8-4aed-8408-cc66528af8f1.png)

**Comment by kamalkech** [comment]
@tjsearsz thank you for you response, i already fixed and i forget to close this post
