### ISSUE TITLE
Command line launcher

### ISSUE THREAD

**Issue by orefalo** [APIs-guru/graphql-voyager#21]

**Comment by IvanGoncharov** [comment]
@orefalo A few questing to clarify your feature request.
Do you want CLI command which launches a local version of our demo(https://apis.guru/graphql-voyager/)?
Or you want CLI command where you pass IDL or URL to your server as arguments and it starts local server which displays only your API?

**Comment by orefalo** [comment]
Ideally a cli command which takes a Json or IDL schema definition would do.

> graphql-voyager myschema.idl

To extend on the feature request, the file pointer could also be a URL, but this could be done with wget. nice to have, not must have

Thank you. Love the tool.

**Comment by RomanGotsiy** [comment]
It is already implemented by [graphql-cli-voyager](https://github.com/graphcool/graphql-cli-voyager)

```sh
npm install -g graphql-cli
npm install -g graphql-cli-voyager
```
setup according to the docs of [graphql-cli](https://github.com/graphcool/graphql-cli) and just run

```sh
graphql voyager
```
