### ISSUE TITLE
displayOptions.skipRelay not evaluated?!

### ISSUE THREAD

**Issue by Michael-Hofer** [APIs-guru/graphql-voyager#23]
Following the readme I'd assume I can set displayOptions when rendering _Voyager_ in the body.
Based on the index.html from the sample I have the following code:
```javascript
      // Render <Voyager /> into the body.
      GraphQLVoyager.init(document.getElementById('voyager'), {
          introspection: introspectionProvider,
          displayOptions: { skipRelay: false, rootType: 'HealthQuery', sortByAlphabet: true }
      });
```
The rendering works fine, but the _skipRelay: false_ option is not considered (_rootType_ and _sortByAlphabet_ are not considered also).
Is something wrong with the _init_ given above or is this a bug?

**Comment by RomanGotsiy** [comment]
Which voyager version are you using?

**Comment by Michael-Hofer** [comment]
I am using version graphql-voyager-1.0.0-rc.0 from the releases page (the files from the dist folder)

**Comment by RomanGotsiy** [comment]
This was a bug in the Readme.
These options were landed in rc.1
Use 1.0.0-rc.3, please.
I have updated README

**Comment by Michael-Hofer** [comment]
Thanks for the advice.
It works fine now with rc.3
