### ISSUE TITLE
Middleware for Node.js frameworks

### ISSUE THREAD

**Issue by steplov** [APIs-guru/graphql-voyager#26]
Hello everybody,

What are you thinking about the idea to add middleware for frameworks like express, koa etc in the same way as apollographql does for graphiql ?
I can take care about this.

**Comment by hmontes** [comment]
Good idea!

**Comment by steplov** [comment]
Ok, fine. Then i will start with the first implementation and later we can discuss how to integrate it to the project.

**Comment by RomanGotsiy** [comment]
@steplov it would be awesome! Let me know if you need any assistance.

**Comment by steplov** [comment]
@RomanGotsiy Hi. I'm almost done with middlewares for express, koa and hapi. But the question is how do you want to distribute them? As for me, the best way is to have monorepo with separate packages for each middleware.

**Comment by steplov** [comment]
@RomanGotsiy , @hmontes hi. I added the first implementation for middleware. Lets review it and discuss what we can improve

**Comment by hmontes** [comment]
I tested today your implementation. CONGRATULATIONS !! Very awesome tool 👍

**Comment by mkochendorfer** [comment]
It appears HAPI 17 is not supported: https://github.com/APIs-guru/graphql-voyager/issues/65
