### ISSUE TITLE
Does not display mutation queries.

### ISSUE THREAD

**Issue by Stoom** [APIs-guru/graphql-voyager#32]
Using the graphql-cli-voyager plugin I noticed that it only shows `query` graphs and is missing `mutation` graphs.

**Comment by IvanGoncharov** [comment]
@Stoom Thank you for the feedback
We need to add a floating menu for settings so you switch between query and mutation.
As a temporary workaround, you can use our [online demo](https://apis.guru/graphql-voyager/) that has to drop down to select root type.

**Comment by RomanGotsiy** [comment]
Closing in favor of #15
