### ISSUE TITLE
update peer dep of graphql to 0.10.x or 0.11.x

### ISSUE THREAD

**Issue by Kosta-Github** [APIs-guru/graphql-voyager#36]
you are already using `graphql` in version `0.10.5` as `dev dep`, but the `peer dep` is still `0.9.x`, can you update the `peer dep` to also work with `0.10.x` and `0.11.x`, please?

**Comment by IvanGoncharov** [comment]
@Kosta-Github Just released `1.0.0-rc.9` with `>=0.9.0` as allowed versions.
Can you please test it?

**Comment by Kosta-Github** [comment]
👍
