### ISSUE TITLE
enhancement - allow import by .graphql file 

### ISSUE THREAD

**Issue by johndpope** [APIs-guru/graphql-voyager#38]
I tried copying and pasting output from graphql   get-schema but no joy. 
should be easier to import.

**Comment by IvanGoncharov** [comment]
@johndpope Great idea 👍
We will definitely implement it for the `1.0.0` release.

**Comment by johndpope** [comment]
presumably done. I'm doing a spring cleaning across older github issues - so going to close this.

**Comment by IvanGoncharov** [comment]
@johndpope Yes SDL is now supported in the demo and `Voyager` component 🎉 
![image](https://user-images.githubusercontent.com/8336157/66075844-1e0ae980-e565-11e9-9c54-628d60057873.png)
