### ISSUE TITLE
build rc7 error on Mac

### ISSUE THREAD

**Issue by hepin1989** [APIs-guru/graphql-voyager#42]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:release' ]
2 info using npm@5.4.2
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild:release', 'build:release', 'postbuild:release' ]
5 info lifecycle graphql-voyager@1.0.0-rc.7~prebuild:release: graphql-voyager@1.0.0-rc.7
6 info lifecycle graphql-voyager@1.0.0-rc.7~build:release: graphql-voyager@1.0.0-rc.7
7 verbose lifecycle graphql-voyager@1.0.0-rc.7~build:release: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-voyager@1.0.0-rc.7~build:release: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kerr/graphql-voyager-1.0.0-rc.7/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle graphql-voyager@1.0.0-rc.7~build:release: CWD: /Users/kerr/graphql-voyager-1.0.0-rc.7
10 silly lifecycle graphql-voyager@1.0.0-rc.7~build:release: Args: [ '-c',
10 silly lifecycle   'npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware' ]
11 silly lifecycle graphql-voyager@1.0.0-rc.7~build:release: Returned: code: 2  signal: null
12 info lifecycle graphql-voyager@1.0.0-rc.7~build:release: Failed to exec build:release script
13 verbose stack Error: graphql-voyager@1.0.0-rc.7 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid graphql-voyager@1.0.0-rc.7
15 verbose cwd /Users/kerr/graphql-voyager-1.0.0-rc.7
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:release"
18 verbose node v6.10.2
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 2
22 error graphql-voyager@1.0.0-rc.7 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
22 error Exit status 2
23 error Failed at the graphql-voyager@1.0.0-rc.7 build:release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by philippeLepage** [comment]
Same with **node 7** : 

0 info it worked if it ends with ok
1 verbose cli [ '/Users/lepp010/.nvm/versions/node/v7.7.3/bin/node',
1 verbose cli   '/Users/lepp010/.nvm/versions/node/v7.7.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:release' ]
2 info using npm@5.3.0
3 info using node@v7.7.3
4 verbose run-script [ 'prebuild:release', 'build:release', 'postbuild:release' ]
5 info lifecycle graphql-voyager@1.0.0-rc.9~prebuild:release: graphql-voyager@1.0.0-rc.9
6 info lifecycle graphql-voyager@1.0.0-rc.9~build:release: graphql-voyager@1.0.0-rc.9
7 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: PATH: /Users/lepp010/.nvm/versions/node/v7.7.3/lib/node_modules/npm/bin/node-gyp-bin:/Users/lepp010/projects/graphQL/graphql-voyager/node_modules/.bin:/Users/lepp010/.nvm/versions/node/v7.7.3/bin:/usr/local/opt/php56/bin:/Users/lepp010/.sdkman/candidates/java/current/bin:/usr/local/bin:/usr/local/sbin:/Users/lepp010/bin:/usr/local/git/bin:/Users/lepp010/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: CWD: /Users/lepp010/projects/graphQL/graphql-voyager
10 silly lifecycle graphql-voyager@1.0.0-rc.9~build:release: Args: [ '-c',
10 silly lifecycle   'npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware' ]
11 silly lifecycle graphql-voyager@1.0.0-rc.9~build:release: Returned: code: 2  signal: null
12 info lifecycle graphql-voyager@1.0.0-rc.9~build:release: Failed to exec build:release script
13 verbose stack Error: graphql-voyager@1.0.0-rc.9 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/lepp010/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/lepp010/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid graphql-voyager@1.0.0-rc.9
15 verbose cwd /Users/lepp010/projects/graphQL/graphql-voyager
16 verbose Darwin 16.7.0
17 verbose argv "/Users/lepp010/.nvm/versions/node/v7.7.3/bin/node" "/Users/lepp010/.nvm/versions/node/v7.7.3/bin/npm" "run" "build:release"
18 verbose node v7.7.3
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error graphql-voyager@1.0.0-rc.9 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
22 error Exit status 2
23 error Failed at the graphql-voyager@1.0.0-rc.9 build:release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by philippeLepage** [comment]
same with **node 8** : 

0 info it worked if it ends with ok
1 verbose cli [ '/Users/lepp010/.nvm/versions/node/v8.8.1/bin/node',
1 verbose cli   '/Users/lepp010/.nvm/versions/node/v8.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:release' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'prebuild:release', 'build:release', 'postbuild:release' ]
5 info lifecycle graphql-voyager@1.0.0-rc.9~prebuild:release: graphql-voyager@1.0.0-rc.9
6 info lifecycle graphql-voyager@1.0.0-rc.9~build:release: graphql-voyager@1.0.0-rc.9
7 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: PATH: /Users/lepp010/.nvm/versions/node/v8.8.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/lepp010/projects/graphQL/graphql-voyager/node_modules/.bin:/Users/lepp010/.nvm/versions/node/v8.8.1/bin:/usr/local/opt/php56/bin:/Users/lepp010/.sdkman/candidates/java/current/bin:/usr/local/bin:/usr/local/sbin:/Users/lepp010/bin:/usr/local/git/bin:/Users/lepp010/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle graphql-voyager@1.0.0-rc.9~build:release: CWD: /Users/lepp010/projects/graphQL/graphql-voyager
10 silly lifecycle graphql-voyager@1.0.0-rc.9~build:release: Args: [ '-c',
10 silly lifecycle   'npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware' ]
11 silly lifecycle graphql-voyager@1.0.0-rc.9~build:release: Returned: code: 2  signal: null
12 info lifecycle graphql-voyager@1.0.0-rc.9~build:release: Failed to exec build:release script
13 verbose stack Error: graphql-voyager@1.0.0-rc.9 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/lepp010/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/lepp010/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid graphql-voyager@1.0.0-rc.9
15 verbose cwd /Users/lepp010/projects/graphQL/graphql-voyager
16 verbose Darwin 16.7.0
17 verbose argv "/Users/lepp010/.nvm/versions/node/v8.8.1/bin/node" "/Users/lepp010/.nvm/versions/node/v8.8.1/bin/npm" "run" "build:release"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 2
22 error graphql-voyager@1.0.0-rc.9 build:release: `npm run clean:release && NODE_ENV=production webpack --config build/webpack.js && rimraf dist/voyager.worker.js.map && npm run build:middleware`
22 error Exit status 2
23 error Failed at the graphql-voyager@1.0.0-rc.9 build:release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by IvanGoncharov** [comment]
@hepin1989 @philippeLepage Sorry for the delay it was a pretty busy month for us.
I will try to investigate this on weekend.

**Comment by RomanGotsiy** [comment]
@hepin1989 @philippeLepage should be fixed now. Could you please verify?

**Comment by philippeLepage** [comment]
@RomanGotsiy   I've tried it and it works now.  Thank you very much.
