### ISSUE TITLE
FR: Skip Deprecated Elements in Graph

### ISSUE THREAD

**Issue by arquio** [APIs-guru/graphql-voyager#47]
As Relay option...

Thanks!

**Comment by felippenardi** [comment]
@IvanGoncharov any chance you are going to work on this soon?

**Comment by IvanGoncharov** [comment]
@felippenardi probably not 😞 maybe next year.

**Comment by romain-gilliotte** [comment]
We also needed this for our project, and I took the time to implement it.
It was pretty straightforward, graphql-voyager code is easy to read.

I'll add a pull request so that it can be reviewed.

**Comment by IvanGoncharov** [comment]
Implemented by @romain-gilliotte in #112 🎉
