### ISSUE TITLE
Middleware does not export TypeScript declarations

### ISSUE THREAD

**Issue by karoun** [APIs-guru/graphql-voyager#48]
Thank you for building such useful tooling for the GraphQL community! One enhancement for users of TypeScript:

The `build:middleware` NPM script should pass `tsc --declaration` so `.d.ts` files will be generated for library consumers.

See also: the [Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) section of the TypeScript handbook

**Comment by IvanGoncharov** [comment]
@karoun Great idea 👍 And thanks for the link.
`1.0.0-rc.11` 📦  now ships with TS typings 🎉
