### ISSUE TITLE
Add ability to add options to the fetch request in loadWorker

### ISSUE THREAD

**Issue by cjmaio** [APIs-guru/graphql-voyager#53]
In cases where you may be behind a single sign on provider, you might need to pass additional options to the `fetch` request inside of `loadWorker`, such as:
```
credentials: 'same-origin'
```
Right now there is no way to do that other than potentially shimming `fetch` globally, which doesn't work for the web worker.

**Comment by IvanGoncharov** [comment]
@cjmaio Don't like to add new options but your use totally makes sense 👍 
What do you think about adding `loadWorker` callback to the `Voyager` tag?

**Comment by cjmaio** [comment]
I've opened a PR - this is my first time with TypeScript so I welcome any suggestions.

**Comment by IvanGoncharov** [comment]
@cjmaio Thanks for PR 👍 
Merged and released as `1.0.0-rc.12` 📦
