### ISSUE TITLE
Undefined GraphQL Voyager in express middleware

### ISSUE THREAD

**Issue by ralphchristianeclipse** [APIs-guru/graphql-voyager#55]
![image](https://user-images.githubusercontent.com/25447231/36289102-18d58988-12f9-11e8-87e2-36f62245026a.png)

I did this

import { express as middleware } from "graphql-voyager/middleware";

app.use("/voyager", middleware({ endpointUrl: "/graphql" }));

but it doesn't work

**Comment by ralphchristianeclipse** [comment]
i think its because of this

https://cdn.jsdelivr.net/npm/graphql-voyager@1.0.0-rc.12/dist/voyager.min.js

![image](https://user-images.githubusercontent.com/25447231/36289184-a0950538-12f9-11e8-980a-6038c4b515a6.png)

**Comment by IvanGoncharov** [comment]
@ralphchristianeclipse Thank you for investigation. I will try to fix it in the morning 🛌 💤

**Comment by IvanGoncharov** [comment]
@ralphchristianeclipse Fixed in 1.0.0-rc.14 📦 
https://cdn.jsdelivr.net/npm/graphql-voyager@1.0.0-rc.14/dist/voyager.min.js
