### ISSUE TITLE
Illegal return statement

### ISSUE THREAD

**Issue by ralphchristianeclipse** [APIs-guru/graphql-voyager#56]
![image](https://user-images.githubusercontent.com/25447231/36316613-ba13d94a-1375-11e8-8e12-ce4fbb3a9e04.png)

Ok the loading bug on js cdn is fixed another bug comes out

**Comment by IvanGoncharov** [comment]
@ralphchristianeclipse Should be fixed in `1.0.0-rc.15`
Can you please confirm that it's working for you?

**Comment by ralphchristianeclipse** [comment]
![image](https://user-images.githubusercontent.com/25447231/36383449-1f829bec-15c7-11e8-89ba-d825ba6bac9d.png)

works now thanks

**Comment by IvanGoncharov** [comment]
@ralphchristianeclipse Thanks for the patience and detailed reports.

BTW. If you decide to make your API public please consider adding it to this list:
https://github.com/APIs-guru/graphql-apis

**Comment by ralphchristianeclipse** [comment]
@IvanGoncharov will do but this one is private :)
