### ISSUE TITLE
How to use the pre-bundled version

### ISSUE THREAD

**Issue by sgaseretto** [APIs-guru/graphql-voyager#58]
I don't know exactly how to use the prebundled version, I tried the following so far

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>

    <link rel="stylesheet" href="./node_modules/graphql-voyager/dist/voyager.css" />
    <script src="./node_modules/graphql-voyager/dist/voyager.min.js"></script>
  </head>
  <body>
    <div id="voyager">Loading...</div>
    <script>
      function introspectionProvider(introspectionQuery) {
        // This example expects a GraphQL server at the path /graphql.
        // Change this to point wherever you host your GraphQL server.
        return fetch('http://127.0.0.1:8000/graphql', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({query: introspectionQuery}),
          credentials: 'include',
        }).then(function (response) {
          return response.text();
        }).then(function (responseBody) {
          try {
            return JSON.parse(responseBody);
          } catch (error) {
            return responseBody;
          }
        });
      }

      // Render <Voyager />
      GraphQLVoyager.init(document.getElementById('voyager'), {
        introspection: introspectionProvider
      })
    </script>
  </body>
</html>
```

What else do I need to do, if I want to use only de CDNs

**Comment by IvanGoncharov** [comment]
@sgaseretto I updated example to use only CDN links:
https://github.com/APIs-guru/graphql-voyager/blob/master/example/index.html
Can you please test it?

**Comment by sgaseretto** [comment]
I just added my endpoint ```http://127.0.0.1:8000/graphql``` again to the new code and it still doesn't work. Probably there is something else I need to do, but I don't know what

**Comment by IvanGoncharov** [comment]
@sgaseretto Can you open dev tools and make a screenshot of the console?

**Comment by IvanGoncharov** [comment]
@sgaseretto If you use HTTP you probably need to remove this line:
```
credentials: 'include',
```

**Comment by sgaseretto** [comment]
This are the errors I'm getting
<img width="1280" alt="captura de pantalla 2018-03-21 a la s 19 17 21" src="https://user-images.githubusercontent.com/6946040/37740463-9c907b7c-2d3c-11e8-90e7-7f6364168d27.png">

**Comment by RomanGotsiy** [comment]
@sgaseretto you are opening page from file-system, that's why `//` in the url is treated as `file:///`.
To fix the issue add `http://` to script urls:

    <script src="https://cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
    <script src="https://cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>

and same for other scripts

**Comment by sgaseretto** [comment]
You were right! Now it seems I'm having a problem with my server
<img width="355" alt="captura de pantalla 2018-03-22 a la s 09 43 54" src="https://user-images.githubusercontent.com/6946040/37771224-b55a5938-2db5-11e8-91ac-893b95790c75.png">
While I figure out what's happening (maybe something related to CORS, despite my backend accepts requests from any IP) how can I modify the bundled version so, instead of fetching, I can embed in it my introspection and visualize it? Maybe this is a dumb question but I'm new to javascript

**Comment by IvanGoncharov** [comment]
@sgaseretto It's because you are opening HTML as file that's why browser can't set `Origin` header.
You should host it somewhere, e.g. run local http server `python -m SimpleHTTPServer`
http://2ality.com/2014/06/simple-http-server.html

**Comment by IvanGoncharov** [comment]
@sgaseretto If you just want to use it locally, try our demo:
https://apis.guru/graphql-voyager/
You can select "Custom introspection" like here:
![image](https://user-images.githubusercontent.com/8336157/37781599-acfe7a8c-2df9-11e8-80c7-6d12d5bd6643.png)

**Comment by IvanGoncharov** [comment]
I'm closing this stale issue.
