### ISSUE TITLE
Koa documentation error

### ISSUE THREAD

**Issue by jamesnmcdowell** [APIs-guru/graphql-voyager#60]
`import { koa as middleware } from 'graphql-voyager/middleware';
router.all('/voyager', voyagerMiddleware({
  endpointUrl: '/graphql'
}));`

voyagerMiddleware does not match up with what is voyager is imported as. voyagerMiddleware should be simply middleware.

**Comment by IvanGoncharov** [comment]
@jamesnmcdowell Thanks for reporting 👍
All samples now use `voyagerMiddleware` 🎉 
I also updated entire middle section hope its become cleaner after that.
