### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by Charius** [APIs-guru/graphql-voyager#61]
Is there any way to integrate this incredible tool into angular project?

I mean there is some info about integration into react project, but nothing about angular

**Comment by IvanGoncharov** [comment]
@Charius I personally never used Angular so I can't answer this question.
If you find a working solution I would happily merge PR that adds `Angular` section to the `README.md`.

**Comment by RomanGotsiy** [comment]
It can't be used without React as it is a React component.

But it can be used with Angular the same way as any other React component can be used with Angular, e.g. you can use [`ReactDOM.render`](https://reactjs.org/docs/integrating-with-other-libraries.html#integrating-with-other-view-libraries) in Angular component [`AfterViewInit` hook](https://angular.io/api/core/AfterViewInit):

```js
import { Component } from '@angular/core';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Voyager } from 'graphql-voyager';


function introspectionProvider(query) {
  // ...
}

@Component({
  //...
})
export class VoyagerWrap {
  constructor(private elRef:ElementRef) {}
  ngAfterViewInit() {
    ReactDOM.render(
      React.createElement(
        Voyager, 
        { introspection: introspectionProvider }
      ),
      this.elRef.nativeElement
    );
  }
}
```

I haven't tested this code. Let us know if you manage to setup it sucessfully. As @IvanGoncharov noted above it would be great to add Angular section to README.

**Comment by Charius** [comment]
@RomanGotsiy thanks, will try to integrate to simple angular project

**Comment by Charius** [comment]
got some kind of luck, but it seems to be worker.js config required, and I'm kinda stuck here

**Comment by RomanGotsiy** [comment]
what the worker.js config? Does it throw any error? Maybe I can help

**Comment by Charius** [comment]
the very first error message posts in console `GET http://localhost:4200/voyager.worker.js 404 (Not Found)`

I know that I can configure workerURI or loadWorker when call `React.createElement`, and I need to figure out how can I import voyager.worker.js into wrapper component and then return it via Promise inside `loadWorker` callback

**Comment by Charius** [comment]
I guess I should try add worker file in angular.json or just use require to obtain it from dist directory

**Comment by RomanGotsiy** [comment]
@Charius you can try adding worker to assets files in `angular.json` and then configure location via workerURI or you can try using `file-loader`, like this:

```js
const myWorkerURI = require('file-loader!graphql-voyager/dist/voyager.worker.js');
```

`file-loader` should emit file to dist directory and you'll get URI in `myWorkerURI`.
Haven't tested it though

**Comment by Charius** [comment]
And btw while doing all this stuff I faced with the problem from https://github.com/graphql/graphql-js/issues/1344

**Comment by NewToStuff** [comment]
To help on the documentation for the Angular section I had to change the first line of @RomanGotsiy s code to the following as ElementRef needs to be imported.

import { Component, ElementRef } from '@angular/core';

**Comment by Charius** [comment]
@NewToStuff Hi there!

In the result about wrapper for voyager I've got something like this:

The component file:

```typescript
import { AfterViewInit, Component, ElementRef, OnInit } from '@angular/core';
import * as React from 'react';
import * as ReactDOM react-dom';
import { Voyager } from 'graphql-voyager';
import { introspectionProvider } from 'src/app/voyager/introspection-provider';

declare var require: any;
const voyagerWorkerURI = require('file-loader!graphql-voyager/dist/voyager.worker.js');

@Component({
  selector: 'app-wrapper',
  templateUrl: './wrapper.component.html',
  styleUrls: ['./wrapper.component.scss']
})
export class WrapperComponent implements OnInit, AfterViewInit {

  constructor(private elementRef: ElementRef) { }

  ngOnInit() { }

  ngAfterViewInit() {
    ReactDOM.render(
      React.createElement(
        Voyager,
        {
          introspection: introspectionProvider,
          workerURI: voyagerWorkerURI
        }
      ),
      this.elementRef.nativeElement);
  }

}

```

angular.json in projects => %project_name% => architect => build => options

```json
...
"styles": [
  "src/styles.scss",
  "node_modules/graphql-voyager/dist/voyager.css"
],

```

`introspectionProvider` is just a function that returns result of `fetch` request to api

**Comment by NewToStuff** [comment]
Thanks @Charius that is really helpful. Got myself confused about how you have set up the introspectionProvider function. It is in a separate typeScript file? How does the structure look?

**Comment by RomanGotsiy** [comment]
@NewToStuff @Charius it is not recommended to import `introspectionProvider` from the package as it is internal and may be removed/renamed/moved in the future.

Just write your own, e.g.:

```js
function introspectionProvider(query) {
  return fetch('<GraphQL endpoint URL here>', {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({query: query}),
  }).then(response => response.json());
}
```

**Comment by NewToStuff** [comment]
Thanks @Charius @RomanGotsiy . I am having a "brain fade" as all my application is in classes and I don't have isolated functions like this. When I am doing the import for the typeScript file which just contains the function above it is complaining that the file being imported is not a module.  I will try to get the bottom of it..

**Comment by Charius** [comment]
@RomanGotsiy I've wrote own provider function, and import is from my file. Anyway thanks for clarification

**Comment by NewToStuff** [comment]
Thanks @Charius @RomanGotsiy . I got this working in the end getting the query result from a Service I established. I ended up sorting the voyager.worker.js issue by adding the following to the assets section within angular-cli.json

        {
          "glob": "voyager.worker.js",
          "input": "../node_modules/graphql-voyager/dist",
          "output": "./"
        },


Looking forward to using this awesome tool.


Thanks

Paul
