### ISSUE TITLE
Announcement! new web server released GAPI! Thank you voyager! :)

### ISSUE THREAD

**Issue by Stradivario** [APIs-guru/graphql-voyager#68]
Hello there guys i am in love with Voyager and i decided to integrate it with my framework it is called @Gapi and you can find more information about the whole namespace here: 
https://github.com/Stradivario/gapi

Gapi-Voyager module is part of this namespace and it can be found at this repository:
https://github.com/Stradivario/gapi-voyager

The main idea behind this Framework is to provide Angular 2+ environment where you can write singleton typescript classes with Dependency Injection and many more features you can read about inside repo readme.It is using GraphQL this is where the name come from GraphQL API aka. GAPI :))

To import graphql voyager inside @Gapi server you need to do the following:

```typescript
import { GapiModule } from '@gapi/core';
import { GapiVoyagerModule } from '@gapi/voyager';

@GapiModule({
    imports: [GapiVoyagerModule]
})
export class CoreModule { }
```

Then you can open http://localhost:9000/voyager it will introspect http://localhost:9000/graphql by default.If you want to specify configuration following example will help you:

```typescript
import { GapiModule } from '@gapi/core';
import { GapiVoyagerModule } from '@gapi/voyager';

@GapiModule({
    imports: [
        GapiVoyagerModule.forRoot({
            path: '/voyager';
            endpointUrl: '/graphql';
        })
    ]
})
export class CoreModule { }
```

You are done! :)

This framework is based on HAPI and you can write Hapi Webserver with Gapi and use Plugins provided by Hapi framework.
Following example will help you to understand how to integrate Hapi plugin inside Gapi.
https://github.com/Stradivario/gapi-voyager/blob/master/development/gapi-voyager-plugin.ts

```typescript
import { GapiVoyagerConfig } from "./gapi-voyager-config";
import { GapiModule, GapiHapiPlugin, GapiHapiPluginInterface } from '@gapi/core';
import renderVoyagerPage from 'graphql-voyager/middleware/render-voyager-page';

@GapiHapiPlugin()
export class VoyagerGapiHapiPlugin implements GapiHapiPluginInterface {
    name = 'VoyagerGapiHapiPlugin';
    version = '1.0.0';

    constructor(
        private config: GapiVoyagerConfig
    ) {}

    async register(server, options) {
        server.route({
            method: 'GET',
            path: this.config.path,
            handler: this.handler.bind(this)
        });
    }

    async handler(_request, reply) {
        return await renderVoyagerPage({ endpointUrl: this.config.endpointUrl });
    }

}

```

Regards,
Kristiyan Tachev

**Comment by RomanGotsiy** [comment]
@Stradivario nice job here 👍
We're glad you like Voyager and integrated it into your framework!
Thanks so much!
