### ISSUE TITLE
Safari compatibility with Viewport:minimal-ui

### ISSUE THREAD

**Issue by cmathews95** [APIs-guru/graphql-voyager#70]
The following error is being returned on running the graphql-voyager middleware on safari.

`[Error] Viewport argument key "minimal-ui" not recognized and ignored. (voyager, line 6)`

From index.html:
`<meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">`.

**Comment by IvanGoncharov** [comment]
@cmathews95 I removed `minimal-ui` and published `v1.0.0-rc.19` 📦 
Can you please try it?

**Comment by RomanGotsiy** [comment]
Feel free to reopen if the issue persists.
