### ISSUE TITLE
Example implementation with graphql-yoga.

### ISSUE THREAD

**Issue by karloluis** [APIs-guru/graphql-voyager#71]
The API I am working on uses graphql-yoga to bootstrap the server and do some pretty cool stuff. Sadly I am not being able to view the voyager as there are a few errors. We would like to visualize the graph and traverse it. Any suggestions or example code available.

PS. The API serves a react-native client.

EDIT: See [here](https://github.com/prismagraphql/graphql-yoga/issues/365) for more details

**Comment by RomanGotsiy** [comment]
@karloluis could you please create minimal reproducible sample?

**Comment by karloluis** [comment]
It seems that my method of authentication makes introspection fail. I will be closing this and move over to the other issue for more details because their example code works fine on a smaller sample.
