### ISSUE TITLE
New Apollo 2.0 server breaks suggested method for middleware with Express

### ISSUE THREAD

**Issue by cmcinroy** [APIs-guru/graphql-voyager#73]
The suggested method for using Voyager as middleware with Express no longer works with the 2.0 release of Apollo.

I followed this approach:
https://github.com/apollographql/apollo-server/issues/1117#issuecomment-397451390

```
import { express as voyagerMiddleware } from 'graphql-voyager/middleware';

const PORT = 3000;

...

const { ApolloServer, gql } = require('apollo-server');
const express = require('express');

const server = new ApolloServer({ typedefs, resolvers });
const app = express();

// Mount voyager middleware
app.use('/voyager', voyagerMiddleware({ endpointUrl: '/graphql' }));
server.applyMiddleware({ app });

app.listen(PORT, () => {
  console.log(`🚀 Server ready at http://localhost:${PORT}${server.graphqlPath}`)
  console.log(`🚀 Subscriptions ready at http://localhost:${PORT}${server.subscriptionsPath}`)
});

```

Only opening this issue here to alert to the Apollo situation... I don't expect anything can or should change with Voyager.

**Comment by daniloferreira** [comment]
You should use apollo-server-express...
I got it working following this doc:
https://www.apollographql.com/docs/apollo-server/essentials/server.html#integrations

**Comment by IvanGoncharov** [comment]
@cmcinroy Thanks for the info.
We are working towards `1.0.0` release and it would be great to include your example in README.
Can you please confirm that it still works with the latest Apollo server?

**Comment by aaronleesmith** [comment]
I can tell you it does work.

**Comment by IvanGoncharov** [comment]
@aaronleesmith Thanks 👍
