### ISSUE TITLE
Option to hide logo

### ISSUE THREAD

**Issue by danpalmer** [APIs-guru/graphql-voyager#81]
I’m looking at embedding Voyager into another page, but the logo takes up a fair bit of room. Would you consider merging a PR that provides an option to hide the logo? I think having it visible would be the best default.

**Comment by IvanGoncharov** [comment]
@danpalmer we are working on a new version of Voyager where you can replace the logo with your own or completely remove. It's already in master but we to finish refactoring in order to release new NPM package.

**Comment by danpalmer** [comment]
Ok, great, I look forward to the next release.

**Comment by IvanGoncharov** [comment]
@danpalmer Thanks for the patience
We completely removed logo in `rc.25`
