### ISSUE TITLE
Free ticket to GraphQL Summit

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/graphql-voyager#94]
Hi guys,

I tagged you all because you contributed to one of `APIs-guru/graphql-*` repos. 

I have a free ticket to GraphQL Summit on Nov 7th & 8th at San Francisco, more details here: https://summit.graphql.com/

If you are interested please leave a comment with email and I will send you a promo code.
**Note: promo code is valid only until Wed Oct 31 5pm PDT**
I only have one ticket so the first **contributor** who leaves a comment will get the ticket.

---------
graphql-voyager: @seangransee @stekycz @brandonbyskov @mkochendorfer @cjmaio @aschepis @soneymathew @kandros @timsuchanek @tuukka @redbass @IzakMarais @LaurenceGA @steplov

graphql-faker: @JamesKyburz @peteruithoven @spawnia @securingsincity @cajames @arquio @ojczeo @amacleay @Archon- @declaneugeneleekennedy @slavik925 @wtgtybhertgeghgtwtg @DonnieWest

graphql-apis: @MikeRalphson @keithpitt @samdenty99 @gfx @jonmhong @gregology @DanielRuf @lightsprint09 @trevorblades @geraldoramos @jelz @vning93 @tuukka @nodkz @operezfuentes @raphaelcosta @mhoffman @jgcmarins

graphql-lodash: @vedmalex @mattleff @nisaacson

**Comment by IvanGoncharov** [comment]
> But I think I won't be able to travel to San Francisco, since I am from Brazil.
But I would love to receive a promo code: jgcmarins@gmail.com

@jgcmarins Just to ensure. Do you already know a person who can and has confirmed that he/she is able to attend this conference. Right?

**Comment by wtgtybhertgeghgtwtg** [comment]
I have no idea how these things work, but I'll take it if it includes lodging.  Or if anyone knows of any nice cardboard boxes in San Francisco.
wtgtybhertgeghgtwtg@gmail.com

**Comment by raphaelcosta** [comment]
I already have a ticket also. Thanks!

**Comment by IvanGoncharov** [comment]
@wtgtybhertgeghgtwtg Could you please confirm that you would be able to attend? 
Just don't want the promo to be wasted

**Comment by wtgtybhertgeghgtwtg** [comment]
Barring any unforeseen accidents, I will be able to attend.

**Comment by jgcmarins** [comment]
Sorry, I can't go and I have no one to indicate

**Comment by IvanGoncharov** [comment]
@jgcmarins NP thanks for response.
@wtgtybhertgeghgtwtg Sent you the promo code, please check your email.

@brandonbyskov @raphaelcosta Looking forward to meeting you at the event.
I will be in the hoodie with big APIs.guru logo at the front.

---------------

# Ticket found it's owner 🎉 Thanks to everyone and sorry for spam.
